## Clock
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

## Switches for inputs A[7:4] and B[3:0]
set_property PACKAGE_PIN J15 [get_ports {sw[0]}]
set_property PACKAGE_PIN L16 [get_ports {sw[1]}]
set_property PACKAGE_PIN M13 [get_ports {sw[2]}]
set_property PACKAGE_PIN R15 [get_ports {sw[3]}]
set_property PACKAGE_PIN R17 [get_ports {sw[4]}]
set_property PACKAGE_PIN T18 [get_ports {sw[5]}]
set_property PACKAGE_PIN U18 [get_ports {sw[6]}]
set_property PACKAGE_PIN R13 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0] sw[1] sw[2] sw[3] sw[4] sw[5] sw[6] sw[7]}]

## LEDs for ExactProduct[7:0] → led[7:0]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property PACKAGE_PIN P14 [get_ports {led[5]}]
set_property PACKAGE_PIN T14 [get_ports {led[6]}]
set_property PACKAGE_PIN H14 [get_ports {led[7]}]

## LEDs for ApproxProduct[7:0] → led[15:8]
set_property PACKAGE_PIN U14 [get_ports {led[8]}]
set_property PACKAGE_PIN T13 [get_ports {led[9]}]
set_property PACKAGE_PIN P15 [get_ports {led[10]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property PACKAGE_PIN V17 [get_ports {led[12]}]
set_property PACKAGE_PIN U17 [get_ports {led[13]}]
set_property PACKAGE_PIN U16 [get_ports {led[14]}]
set_property PACKAGE_PIN V16 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0] led[1] led[2] led[3] led[4] led[5] led[6] led[7] led[8] led[9] led[10] led[11] led[12] led[13] led[14] led[15]}]

## 7-Segment Display Segments [a-g] → seg[6:0]
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property PACKAGE_PIN V6 [get_ports {seg[2]}]
set_property PACKAGE_PIN U6 [get_ports {seg[3]}]
set_property PACKAGE_PIN V5 [get_ports {seg[4]}]
set_property PACKAGE_PIN U5 [get_ports {seg[5]}]
set_property PACKAGE_PIN R5 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0] seg[1] seg[2] seg[3] seg[4] seg[5] seg[6]}]

## 7-Segment Display Anodes [3:0] → an[3:0]
set_property PACKAGE_PIN U4 [get_ports {an[0]}]
set_property PACKAGE_PIN V4 [get_ports {an[1]}]
set_property PACKAGE_PIN W4 [get_ports {an[2]}]
set_property PACKAGE_PIN W5 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0] an[1] an[2] an[3]}]
